version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_LANG: "ru_RU.utf8"
      POSTGRES_EXTENSIONS: pg_cron

    ports:
      - "45432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "48080:8080"